name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          exec $SHELL
      - name: Export requirements
        run: poetry export -f requirements.txt --output requirements.txt
      - name: Download python 3.8.10
        run:  wget https://www.python.org/ftp/python/3.8.10/python-3.8.10-embed-amd64.zip
      - name: Unzip python
        run: unzip python-3.8.10-embed-amd64.zip -d python-3.8.10
      - name: Download pip
        run: wget https://bootstrap.pypa.io/get-pip.py -P python-3.8.10
      - name: Create install batch file
        run: echo -en "@echo off\npython-3.8.10\python.exe get-pip.py\npython-3.8.10\Scripts\pip.exe install requirements.txt" > install.bat
      - name: Create run batch file
        run: echo -en "@echo off\npython-3.8.10\python.exe ..\controller.py" > bin/run.bat
      - name: Create run vbs script
        run: echo -en "Set objShell = WScript.CreateObject("WScript.Shell")\nobjShell.Run(\"bin\run.bat"), 0, True" > run.vbs
      - name: Create ZIP archive
        run: |
          md dist
          zip -r dist/autocad-polystyrene-calculatio-x64 ./ -x *.git* mypy.ini poetry.lock .editorconfig
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
