from PyQt6 import QtCore, QtWidgets, QtGui
import os
import sys


class Ui_Form(object):
    def setupUi(self, Form: QtWidgets.QWidget):
        Form.setObjectName("Form")
        Form.resize(403, 889)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.init_data = QtWidgets.QGroupBox(Form)
        self.init_data.setCheckable(False)
        self.init_data.setObjectName("init_data")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.init_data)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.init_data)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.init_data_scale = QtWidgets.QLineEdit(self.init_data)
        self.init_data_scale.setObjectName("init_data_scale")
        self.verticalLayout_6.addWidget(self.init_data_scale)
        self.label = QtWidgets.QLabel(self.init_data)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.init_data_thickness = QtWidgets.QLineEdit(self.init_data)
        self.init_data_thickness.setObjectName("init_data_thickness")
        self.verticalLayout_6.addWidget(self.init_data_thickness)
        self.init_data_type = QtWidgets.QGroupBox(self.init_data)
        self.init_data_type.setObjectName("init_data_type")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.init_data_type)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.init_data_type_1 = QtWidgets.QRadioButton(self.init_data_type)
        self.init_data_type_1.setChecked(True)
        self.init_data_type_1.setObjectName("init_data_type_1")
        self.verticalLayout_2.addWidget(self.init_data_type_1)
        self.init_data_type_2 = QtWidgets.QRadioButton(self.init_data_type)
        self.init_data_type_2.setObjectName("init_data_type_2")
        self.verticalLayout_2.addWidget(self.init_data_type_2)
        self.verticalLayout_6.addWidget(self.init_data_type)
        self.init_data_table = QtWidgets.QTreeWidget(self.init_data)
        self.init_data_table.setObjectName("init_data_table")
        self.verticalLayout_6.addWidget(self.init_data_table)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.init_data_add = QtWidgets.QPushButton(self.init_data)
        self.init_data_add.setObjectName("init_data_add")
        self.horizontalLayout_2.addWidget(self.init_data_add)
        self.init_data_delete = QtWidgets.QPushButton(self.init_data)
        self.init_data_delete.setObjectName("init_data_delete")
        self.horizontalLayout_2.addWidget(self.init_data_delete)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.choose_autocad_el = QtWidgets.QPushButton(self.init_data)
        self.choose_autocad_el.setObjectName("choose_autocad_el")
        self.verticalLayout_6.addWidget(self.choose_autocad_el)
        self.verticalLayout_3.addWidget(self.init_data)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget_2.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.tableWidget_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_7.addWidget(self.lineEdit_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_7.addWidget(self.lineEdit_4)
        self.verticalLayout_5.addWidget(self.groupBox_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout.addWidget(self.pushButton_8)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.groupBox_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form: QtWidgets.QWidget):
        app_icon = QtGui.QIcon(os.path.join(sys.path[1], "assets", "logo.png"))
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Раскладка утеплителя"))
        Form.setWindowIcon(app_icon)
        self.init_data.setTitle(_translate("Form", "Исходные данные"))
        self.label_2.setText(_translate("Form", "Масштаб"))
        self.label.setText(_translate("Form", "Толщина ППТ"))
        self.init_data_type.setTitle(_translate("Form", "Тип"))
        self.init_data_type_1.setText(_translate("Form", "ППТ-15-А-Р"))
        self.init_data_type_2.setText(_translate(
            "Form", "Эффективный утеплитель λ ≤ 0,034 Вт/(м·°C)"))
        self.init_data_table.headerItem().setText(0, _translate("Form", "Толщина"))
        self.init_data_table.headerItem().setText(1, _translate("Form", "Тип"))
        self.init_data_add.setText(_translate("Form", "Добавить"))
        self.init_data_delete.setText(_translate("Form", "Удалить"))
        self.choose_autocad_el.setText(_translate("Form", "Выбрать позиции ППТ"))
        self.groupBox_3.setTitle(_translate("Form", "Результат"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Поз."))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Обозначение"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Наименование"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Кол., шт."))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Объем, м3"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Примечания"))
        self.pushButton_4.setText(_translate(
            "Form", "Экспорт таблицы в AutoCAD"))
        self.pushButton_3.setText(_translate("Form", "Удалить позицию"))
        self.pushButton_5.setText(_translate(
            "Form", "Экспорт таблицы в Excel"))
        self.pushButton_6.setText(_translate(
            "Form", "Отрисовать пакеты в AutoCAD"))
        self.groupBox_4.setTitle(_translate("Form", "Отходы"))
        self.groupBox_5.setTitle(_translate("Form", "Общий объем ППТ"))
        self.label_3.setText(_translate("Form", "ППТ-15"))
        self.label_4.setText(_translate("Form", "Эффективный"))
        self.pushButton_7.setText(_translate(
            "Form", "Рассчиать и вывести на лист"))
        self.pushButton_8.setText(_translate("Form", "Отрисовать раскрой"))
